server:
  port: 8081
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/
    username: root
    password: root
    driver-class-name: com.mysql.jdbc
limit:
  minMoney: 10
  maxMoney: 9999
  description: 最少要发${limit.minMoney}块钱,最多${limit.maxMoney}元
